### ISSUE TITLE
Console error occurred (Context unknown)

### ISSUE THREAD

**Issue by kns5928** [ItzMace/LastMinerStanding-DEV#115]
Error occurred (context unknown):

```
[11:12:38 ERROR]: Could not pass event PlayerInteractEvent to LastMinerStanding v2.0.5-b1
org.bukkit.event.EventException
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:917) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_161]
at implements.do(Unknown Source) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor806.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
... 18 more
```

### Core information
**Spigot version**: 1.11.2 PaperSpigot b1104

**LMS version**: 2.0.5-b1

**Plugin list**: CMI , WorldEdit , CrackShot , CrackShotPLUS , LastMinerStanding , ViaVersion

### Special environment information

**ViaVersion version**: Yes, Version 1.3.0 is installed.

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

***Note by M4CE:** Investigation required.*

**Comment by ItzMace** [comment]
Not reproduceable.
