### ISSUE TITLE
Getting error by typing every command (#51)

### ISSUE THREAD

**Issue by ViinexxYT** [ItzMace/LastMinerStanding-DEV#191]
Everytime, i type a Command a internal Error occures. In Console is:

[19:01:13] [Server thread/WARN]: [LastMinerStanding] Task #51 for LastMinerStanding v2.1.0 generated an exception
java.lang.NullPointerException: null
	at me.M4CE.LastMinerStanding.LastMinerStanding.if(Unknown Source) ~[?:?]
	at me.M4CE.LastMinerStanding.byte.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-7754231-94b0980]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

### Core information
**Spigot version**: 1.12.2

**LMS version**: newest

**Plugin list**: Too many xD

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: newest

**ProtocolSupport version**: insert

**ViaBackwards version**: newest

**BungeeCord plugins**: insert

**Comment by ItzMace** [comment]
Issue fixed. (@Discord)
