### ISSUE TITLE
Crackshot causing error on game start

### ISSUE THREAD

**Issue by ItzMace** [ItzMace/LastMinerStanding-DEV#40]
### Issue description

> On game start
> dont get tped anywhere
> found out its crackshot
> crackshot is what i need to
> crackshot isnt working with lastminer

> Yes. it does when i change those settings it crashes. i cant test it rn the ded server host is down for some reason but. as soon as i touched anything with crackshot it crashes
> but ichanged the items.yml to the guns i made
> and it still crashed
> with the error in console with task 8
> once my server comes up ill test again

```06.01 21:06:52 [Server] WARN [LastMinerStanding] Task #4 for LastMinerStanding v1.1.14 generated an exception
06.01 21:06:52 [Server] INFO java.lang.NullPointerException: null
06.01 21:06:52 [Server] INFO at me.M4CE.LastMinerStanding.LastMinerStanding.byte(Unknown Source) ~[?:?]
06.01 21:06:52 [Server] INFO at me.M4CE.LastMinerStanding.LastMinerStanding.if(Unknown Source) ~[?:?]
06.01 21:06:52 [Server] INFO at me.M4CE.LastMinerStanding.do.run(Unknown Source) ~[?:?]
06.01 21:06:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
```

### Core information
**Spigot version**: 1.8.8

**LMS version**: 1.1.14

**Plugin list**: LastMinerStanding, ViaVersion

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.3.0

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by ItzMace** [comment]
Not reproduceable. 
The error seems to occure due to an issue in the scoreboard.yml file.
All class files involved had nothing to do with Crackshot.
